# This is a configuration file for the bacon tool
# More info at https://github.com/Canop/bacon

default_job = "test2022"

[jobs]

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--color", "always"]
need_stdout = false

[jobs.test2020]
command = [
    "cargo",
    "test",
    "--color",
    "always",
    "--release",
    "--bin",
    "aoc2020",
]
need_stdout = true
allow_warnings = true
watch = ["src/bin/aoc2020"]

[jobs.test2021]
command = [
    "cargo",
    "test",
    "--color",
    "always",
    "--release",
    "--bin",
    "aoc2021",
]
need_stdout = true
allow_warnings = true
watch = ["src/bin/aoc2021"]

[jobs.test2022]
command = [
    "cargo",
    "test",
    "--color",
    "always",
    "--release",
    "--bin",
    "aoc2022",
]
need_stdout = true
allow_warnings = true
watch = ["src/bin/aoc2022"]

[jobs.bench2020]
command = ["cargo", "bench", "--color", "always", "--bin", "aoc2020"]
need_stdout = true
allow_warnings = true
watch = ["src/bin/aoc2020"]

[jobs.bench2021]
command = ["cargo", "bench", "--color", "always", "--bin", "aoc2021"]
need_stdout = true
allow_warnings = true
watch = ["src/bin/aoc2021"]

[jobs.bench2022]
command = ["cargo", "bench", "--color", "always", "--bin", "aoc2022"]
need_stdout = true
allow_warnings = true
watch = ["src/bin/aoc2022"]

# if the doc compiles, then it opens in your browser and bacon switches
# to the previous job
[jobs.doc]
command = ["cargo", "doc", "--color", "always", "--no-deps", "--open"]
need_stdout = false
on_success = "back"                                                    # so that we don't open the browser at each change

# You may define here keybindings that would be specific to
# a project, for example a shortcut to launch a specific job.
# Shortcuts to internal functions (scrolling, toggling, etc.)
# should go in your personal prefs.toml file instead.
[keybindings]
0 = "job:test2020"
1 = "job:test2021"
2 = "job:test2022"
z = "job:bench2020"
x = "job:bench2021"
c = "job:bench2022"
